// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPiBFBS7UDk38-12wfp7R2Ead2rYceeGA',
    appId: '1:66114167783:web:079f69adaf5bc792c8d342',
    messagingSenderId: '66114167783',
    projectId: 'bestartup-680d0',
    authDomain: 'bestartup-680d0.firebaseapp.com',
    databaseURL: 'https://bestartup-680d0-default-rtdb.firebaseio.com',
    storageBucket: 'bestartup-680d0.appspot.com',
    measurementId: 'G-BK08G8BZ0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtttUX-COBJxHnE4VzQg8Heo2dzEJFwY0',
    appId: '1:66114167783:android:cc08ce23db617b87c8d342',
    messagingSenderId: '66114167783',
    projectId: 'bestartup-680d0',
    databaseURL: 'https://bestartup-680d0-default-rtdb.firebaseio.com',
    storageBucket: 'bestartup-680d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDudoF2LUYljnwjrGg0yquOxmb7bVXU3e8',
    appId: '1:66114167783:ios:85fafd8d9dd170b3c8d342',
    messagingSenderId: '66114167783',
    projectId: 'bestartup-680d0',
    databaseURL: 'https://bestartup-680d0-default-rtdb.firebaseio.com',
    storageBucket: 'bestartup-680d0.appspot.com',
    androidClientId: '66114167783-nialhmegnjuj3b4f3kt8urjqfnmrbjo0.apps.googleusercontent.com',
    iosClientId: '66114167783-b2est4ve6hih3f48320vic8khv9glkvd.apps.googleusercontent.com',
    iosBundleId: 'com.vishalshakayaproject.bestartup',
  );
}
