// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQk5FEXKcdxpA-W5_hjZJR1sR1c7WQS4w',
    appId: '1:398783146658:web:79f97a77fc799753c4c5fb',
    messagingSenderId: '398783146658',
    projectId: 'sharkstartup',
    authDomain: 'sharkstartup.firebaseapp.com',
    databaseURL: 'https://sharkstartup-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sharkstartup.appspot.com',
    measurementId: 'G-TYKMNVW3ZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9r_moCdQYlwTS5D_A746yfZYhqwSkWio',
    appId: '1:398783146658:android:609a497ce2999419c4c5fb',
    messagingSenderId: '398783146658',
    projectId: 'sharkstartup',
    databaseURL: 'https://sharkstartup-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sharkstartup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLEpDfPcOTk0uQFDaA_64ELxqgQEdL-5I',
    appId: '1:398783146658:ios:7005add74f117d04c4c5fb',
    messagingSenderId: '398783146658',
    projectId: 'sharkstartup',
    databaseURL: 'https://sharkstartup-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sharkstartup.appspot.com',
    iosClientId: '398783146658-upeiha7m928vnbq4pev1lff674d9ut07.apps.googleusercontent.com',
    iosBundleId: 'com.vishalshakayaproject.bestartup',
  );
}
